name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 🔥 Оце ключове
    environment: ${{ github.ref_name }}
    env:
      NAME_ENV: ${{ vars.NAME_ENV }}
    steps:
      - uses: actions/checkout@v4

      - name: Show current branch
        run: echo "Branch is ${{ github.ref_name }}"

      - name: Show environment variable
        run: echo "NAME_ENV=$NAME_ENV"
