name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 🔥 Оце ключове
    environment: ${{ github.ref_name }}
    env:
      NAME_ENV: ${{ vars.NAME_ENV }}
      ALLENV: ${{ vars.ALLENV }}
      ENV1: ${{ vars.ENV1 }}
    steps:
      - uses: actions/checkout@v4

      - name: Show current branch
        run: echo "Branch is ${{ github.ref_name }}"

      - name: Show environment variable
        run: echo "NAME_ENV=$NAME_ENV"
      
      - name: Show all variable
        run: echo "ALLENV=$ALLENV"
        
      - name: Show all remaped env
        run: echo "ENV1=$ENV1"
